#!/usr/bin/env bash

set -o pipefail

if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be started using sudo"
   exit 1
fi

if [ -f .env ]; then
  source .env
fi

if [ -z "${TIMEZONE}" ]; then
  TIMEZONE="Europe/Berlin"
fi

if [ -z "${KEYMAP}" ]; then
  KEYMAP="de-latin1"
fi

if [ -z "${LOCALE}" ]; then
  LOCALE="en_US.UTF-8 UTF-8"
fi

if [ -z "${HOST_NAME}" ]; then
  HOST_NAME="archlinux-ci"
fi

if [ -z "${IMAGE_SIZE}" ]; then
  IMAGE_SIZE=50G
fi

IMAGE_NAME="arch-linux-x86_64-cloudinit-ext4"
RAW="${IMAGE_NAME}.raw"
QCOW="${IMAGE_NAME}.qcow2"

# Check if we run in a GitHub action
echo "${QCOW}" > artifact_name.txt

REAL_USER=${SUDO_USER:-$(whoami)}
REAL_GROUP=${SUDO_GID:-$(id -g "$REAL_USER")}

truncate -s "${IMAGE_SIZE}" "${RAW}"
losetup -fP "${RAW}"

# shellcheck disable=SC2155
ARCH_LOOP=$(losetup -j "${RAW}" | cut -d : -f 1)
ARCH_LOOPp1="${ARCH_LOOP}p1"
ARCH_LOOPp2="${ARCH_LOOP}p2"

MNT=mnt
BOOT="${MNT}/boot"

if [ ! -d "${MNT}" ]; then
    echo "Create mnt ${MNT}..."
    mkdir -p "${MNT}"
fi

sfdisk "${ARCH_LOOP}" <<EOF
label: gpt
unit: sectors
first-lba: 2048

# 1. EFI System Partition (Size: 200.000 sectors ≈ 100 MiB)
: size=524288, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name="EFI"

# 2. Linux Root Partition (rest of the disk)
: type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, name="root"
EOF

mkfs.fat -F 32 "${ARCH_LOOPp1}"
mkfs.ext4 "${ARCH_LOOPp2}"
EFI_UUID=$(blkid -s UUID -o value "${ARCH_LOOPp1}")
ROOT_UUID=$(blkid -s UUID -o value "${ARCH_LOOPp2}")

mount "${ARCH_LOOPp2}" "${MNT}"
mkdir "${BOOT}"
mount "${ARCH_LOOPp1}" "${BOOT}"

pacstrap -P -K "${MNT}/" base \
  linux \
  openssh \
  sudo \
  dosfstools \
  efibootmgr \
  cloud-init \
  qemu-guest-agent \
  cloud-guest-utils

cat <<EOF > "./${MNT}/etc/fstab"
# Static fstab generated by CI Build
UUID=$EFI_UUID /boot vfat defaults 0 2
UUID=$ROOT_UUID / ext4 defaults 0 1
EOF

# chroot into the system and configure it
arch-chroot "${MNT}/" <<EOF
# Set timezone
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime
hwclock --systohc

# Set locale and keymap
echo "${LOCALE}" >> /etc/locale.gen
echo "KEYMAP=${KEYMAP}" > /etc/vconsole.conf
locale-gen

# Set hostname
echo "${HOST_NAME}" > /etc/hostname

# Set hooks for systemd and create initramfs
sed -i 's/^HOOKS=(.*/HOOKS=(systemd modconf kms sd-vconsole block filesystems fsck)/' /etc/mkinitcpio.conf
mkinitcpio -P

# systemd bootloader Installation
bootctl install

rm /etc/resolv.conf
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

# Activate services
systemctl enable \
  systemd-networkd.service \
  systemd-resolved.service \
  systemd-timesyncd \
  systemd-time-wait-sync \
  cloud-init-local.service \
  cloud-init.service
  cloud-config.service \
  cloud-final.service \
  sshd \
  qemu-guest-agent

# Cleanup
pacman -Scc --noconfirm
rm -rf /var/cache/pacman/pkg/*
rm -rf /var/log/*
rm -rf /tmp/*

rm /etc/machine-id

## Nullify whole remaining space
dd if=/dev/zero of=zero.fill bs=1M || true
dd if=/dev/zero of=/boot/zero.fill bs=1M || true
rm zero.fill
rm /boot/zero.fill
EOF

# Configure cloudinit
mkdir -p "./${MNT}/etc/cloud/cloud.cfg.d"
cat <<EOF > "./${MNT}/etc/cloud/cloud.cfg.d/99-network-renderer.cfg"
network:
  method: systemd-networkd
EOF
#cat <<EOF > "./${MNT}/etc/cloud/cloud.cfg.d/10_arch_network.cfg"
#system_info:
#   network:
#      renderers: ['networkd']
#EOF
# Avoid clearing network config after each reboot
#echo "network: {config: disabled}" > "./${MNT}/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"

# Create boot loader entries
cat <<EOF > "./${MNT}/boot/loader/loader.conf"
default  arch.conf
timeout  0
console-mode max
editor   no
EOF

cat <<EOF > "./${MNT}/boot/loader/entries/arch.conf"
title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=UUID=${ROOT_UUID} rw
EOF

sync

# Unmount file system
umount "${BOOT}"
umount "${MNT}/"
losetup -d "${ARCH_LOOP}"

# Convert raw image to qcow2 and cleanup
qemu-img convert -c -f raw -O qcow2 "${RAW}" "${QCOW}"
rm "${RAW}"
chown "$REAL_USER":"$REAL_GROUP" "${QCOW}"
