name: Build Arch Linux QCOW2 Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build in Arch Container
        id: build_step
        run: |
          # Manually start Arch container and mount dev of host
          docker run --privileged --rm \
            -v /dev:/dev \
            -v $(pwd):/build \
            archlinux:latest \
            /bin/bash -c "pacman -Syu --noconfirm arch-install-scripts qemu-base dosfstools e2fsprogs; cd /build; ./build.sh"
          cat ./artifact_name.txt
          cat ./artifact_name.txt >> $GITHUB_OUTPUT

      - name: Upload qcow2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.IMAGE_NAME }}
          path: ./${{ steps.build_step.outputs.IMAGE_NAME }}
          if-no-files-found: error
          retention-days: 30

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            "./${{ steps.build_step.outputs.IMAGE_NAME }}" \
            --title "${GITHUB_REF_NAME}" \
            --notes "Automatically generated image on $(date +%d.%m.%Y)" \
            --generate-notes \
            --clobber
