name: Build Arch Linux QCOW2 Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build in Arch Container
        run: |
          # Manually start Arch container and mount dev of host
          docker run --privileged --rm \
            -e "GITHUB_OUTPUT=/github-output" \
            -v "$GITHUB_OUTPUT:/github-output" \
            -v /dev:/dev \
            -v $(pwd):/build \
            archlinux:latest \
            /bin/bash -c "pacman -Syu --noconfirm arch-install-scripts qemu-base dosfstools e2fsprogs; cd /build; ./build.sh"

      - name: Debug
        run: |
          echo "Image: ${{ steps.build_step.outputs.IMAGE_NAME }}"

#      - name: Upload qcow2 artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ steps.build_step.outputs.IMAGE_NAME }}
#          path: ./${{ steps.build_step.outputs.IMAGE_NAME }}
#          if-no-files-found: error
#          retention-days: 30