name: Build Arch Linux QCOW2 Image

on:
  push:
    branches:
      - main
    tags:
      - 'release-*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build in Arch Container
        id: build_step
        run: |
          # Manually start Arch container and mount dev of host
          docker run --privileged --rm \
            -v /dev:/dev \
            -v $(pwd):/build \
            archlinux:latest \
            /bin/bash -c "pacman-key --init; pacman -Syu --noconfirm arch-install-scripts qemu-base dosfstools e2fsprogs; cd /build; ./build.sh"
          ls -la
          IMAGE_NAME="$(cat ./artifact_name.txt)"
          echo "${IMAGE_NAME}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          sha256sum "${IMAGE_NAME}" > "${IMAGE_NAME}.SHA256"

      - name: Upload qcow2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.IMAGE_NAME }}
          path: |
            ./${{ steps.build_step.outputs.IMAGE_NAME }}
            ./${{ steps.build_step.outputs.IMAGE_NAME }}.SHA256
          if-no-files-found: error
          retention-days: 3

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/release')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            "./${{ steps.build_step.outputs.IMAGE_NAME }}" \
            "./${{ steps.build_step.outputs.IMAGE_NAME }}.SHA256" \
            --title "${GITHUB_REF_NAME}" \
            --notes "Automatically generated image on $(date +%d.%m.%Y)" \
            --generate-notes
